"""
decoder_only_detector_diagnostic.py

Time-critical final diagnostic for downstream reasoning feasibility.
Tests whether the existing ASR Error Detector B can identify decoder-level 
lexical errors when the Whisper ENCODER REPRESENTATION IS HELD FIXED.
"""

import os
import re
import json
import warnings
import numpy as np
import pandas as pd
import librosa
import torch
import whisper
import joblib
from pathlib import Path
from tqdm import tqdm
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, auc, precision_recall_curve, confusion_matrix
from scipy.spatial.distance import jensenshannon
from sentence_transformers import SentenceTransformer
import torch.nn as nn
import torch.nn.functional as F

# Authoritative feature extractor from training
from feature_extractor import extract_baseline_features

warnings.filterwarnings("ignore")

# ==========================================
# 0. CONFIGURATION & PATHS
# ==========================================
ROOT_DIR = Path("/home/spark2/users/intern/Atreyee-Das/NLU_Robust_Experiment")
EVAL_DATASET_CSV = ROOT_DIR / "dataset" / "whisper_domain_multitarget_6000.csv"
GROUND_TRUTH_SEMANTIC_CSV = ROOT_DIR / "dataset" / "robus_nlu_6000_paraphrase_scenario.csv"

# Check possible audio directories
AUDIO_DIRS = [
    ROOT_DIR / "audio",
    ROOT_DIR / "audios",
    ROOT_DIR / "dataset" / "audio"
]

WHISPER_MODEL_PATH = "/home/spark2/Models/base.en.pt"
VOICE_MODELS_DIR = ROOT_DIR / "audio_nlu_models"
TEXT_MODELS_DIR = ROOT_DIR / "text_nlu_models"
TEXT_ENCODER_PATH = "/home/spark2/Models/all-MiniLM-L6-v2"

# Artifacts generated by run_master_exp.py
EXP_BASE = ROOT_DIR / "error_detector_experiments"
MODELS_CACHE_DIR = EXP_BASE / "artifacts" / "models"
DETECTOR_B_PATH = MODELS_CACHE_DIR / "controlled_detector_B.joblib"
THRESHOLDS_PATH = MODELS_CACHE_DIR / "controlled_detector_B_threshold.json"
FEATURES_PATH = MODELS_CACHE_DIR / "controlled_detector_B_features.json"

EXP_DIR = Path("decoder_only_detector_diagnostic")
for sub in ["results", "posterior_npz", "representative", "figures", "logs"]:
    (EXP_DIR / sub).mkdir(parents=True, exist_ok=True)

HEADS = ["domain", "subdomain", "topic", "document_type"]
DECODER_TEMPS = [0.0, 0.2, 0.4, 0.6, 0.8]

# ==========================================
# 1. ARCHITECTURE DEFINITIONS
# ==========================================
class VoiceHierarchicalProjection(nn.Module):
    def __init__(self, input_dim=512, projection_dim=128):
        super().__init__()
        self.projector = nn.Sequential(
            nn.Linear(input_dim, 256),
            nn.ReLU(),
            nn.Dropout(0.10),
            nn.Linear(256, projection_dim),
        )
    def forward(self, x):
        z = self.projector(x)
        return F.normalize(z, p=2, dim=1)

class TextHierarchicalProjection(nn.Module):
    def __init__(self, input_dim=384, projection_dim=128):
        super().__init__()
        self.projector = nn.Sequential(
            nn.Linear(input_dim, 256),
            nn.ReLU(),
            nn.Dropout(0.10),
            nn.Linear(256, projection_dim),
        )
    def forward(self, x):
        z = self.projector(x)
        return F.normalize(z, p=2, dim=1)

# ==========================================
# 2. DISTRACTOR & TEXT HELPERS
# ==========================================
CANDIDATE_DISTRACTORS = {
    "medical": [
        "myocardial ischemia", "cardiac insufficiency", "coronary stenosis", 
        "ventricular arrhythmia", "pericardial inflammation", "arterial occlusion", 
        "vascular calcification", "cardiac electrophysiology", "pulmonary embolism", 
        "hemodynamic instability"
    ],
    "finance": [
        "claims adjudication", "provider reimbursement", "premium reconciliation", 
        "medical billing adjustment", "benefit authorization", "clinical payment settlement", 
        "payer reconciliation", "hospital revenue cycle", "insurance eligibility", 
        "healthcare reimbursement", "algorithmic trading", "digital asset custody", 
        "technology investment banking", "cloud infrastructure financing", 
        "software revenue recognition", "electronic settlement", "cybersecurity financing", 
        "technology capital allocation", "digital payment infrastructure", "fintech risk management",
        "industrial procurement", "manufacturing capital expenditure", "equipment depreciation", 
        "supply chain financing", "factory asset valuation", "industrial inventory turnover", 
        "machinery leasing", "production capacity financing", "commodity procurement", 
        "industrial working capital"
    ],
    "general": [
        "appointment confirmation", "reservation cancellation", "customer service request", 
        "delivery notification", "account verification", "schedule modification", 
        "payment confirmation", "booking information", "service availability", "order confirmation"
    ]
}

def normalize_text(text):
    if not isinstance(text, str): return ""
    text = text.lower()
    text = re.sub(r'[^\w\s]', '', text)
    text = re.sub(r'\s+', ' ', text)
    return text.strip()

def build_dataset_vocabulary(dfs):
    vocab = set()
    for df in dfs:
        if df is None: continue
        text_cols = [c for c in df.columns if any(k in c.lower() for k in ['transcript', 'target', 'term', 'word', 'text', 'prompt', 'domain', 'topic', 'subdomain', 'document', 'label'])]
        for col in text_cols:
            for val in df[col].dropna():
                norm_val = normalize_text(str(val))
                vocab.update(norm_val.split())
    return vocab

def find_audio_file(sample_id):
    for adir in AUDIO_DIRS:
        if not adir.exists(): continue
        candidates = [
            adir / f"{sample_id}.wav",
            adir / f"{sample_id}",
            adir / f"sample_{sample_id}.wav",
            adir / f"{sample_id}.flac"
        ]
        for p in candidates:
            if p.exists():
                return p
    return None

def check_target_corruption(candidate_text, target_term):
    cand_norm = normalize_text(candidate_text)
    targ_norm = normalize_text(target_term)
    
    targ_tokens = targ_norm.split()
    cand_tokens = cand_norm.split()
    
    if not targ_tokens: return 0, 0, 0.0, 0, 0
        
    target_token_count = len(targ_tokens)
    target_tokens_preserved = sum(1 for t in targ_tokens if t in cand_tokens)
    target_corruption_rate = 1.0 - (target_tokens_preserved / target_token_count)
    exact_target_preserved = 1 if targ_norm in cand_norm else 0
    target_was_corrupted = 1 if target_corruption_rate > 0 else 0
    
    return target_token_count, target_tokens_preserved, target_corruption_rate, exact_target_preserved, target_was_corrupted

def eval_metrics(df_subset):
    if len(df_subset) == 0:
        return 0, 0, 0, 0, 0, np.zeros((2,2))
    y_true = (df_subset['corruption_level'] > 0).astype(int)
    y_prob = df_subset['detector_probability']
    y_pred = df_subset['detector_prediction']
    
    prec = precision_score(y_true, y_pred, zero_division=0)
    rec = recall_score(y_true, y_pred, zero_division=0)
    f1 = f1_score(y_true, y_pred, zero_division=0)
    
    if len(np.unique(y_true)) > 1:
        roc_auc = roc_auc_score(y_true, y_prob)
        p, r, _ = precision_recall_curve(y_true, y_prob)
        pr_auc = auc(r, p)
    else:
        roc_auc = pr_auc = float('nan')
        
    cm = confusion_matrix(y_true, y_pred, labels=[0, 1])
    return prec, rec, f1, roc_auc, pr_auc, cm

# ==========================================
# 3. MAIN EXPERIMENT
# ==========================================
def run_diagnostic():
    print("="*60 + "\nPART 1: ARTIFACT AUDIT & LOADING\n" + "="*60)
    device = "cuda" if torch.cuda.is_available() else "cpu"
    
    # 1. Load Datasets
    assert EVAL_DATASET_CSV.exists(), f"Missing evaluation dataset: {EVAL_DATASET_CSV}"
    df_eval_raw = pd.read_csv(EVAL_DATASET_CSV)
    df_gt_raw = pd.read_csv(GROUND_TRUTH_SEMANTIC_CSV) if GROUND_TRUTH_SEMANTIC_CSV.exists() else None
    
    # 2. Build Dataset Vocabulary & Distractor Filter
    dataset_vocab = build_dataset_vocabulary([df_eval_raw, df_gt_raw])
    valid_distractors = {}
    total_candidates = 0
    excluded_count = 0
    
    for dom, terms in CANDIDATE_DISTRACTORS.items():
        valid_distractors[dom] = []
        for term in terms:
            total_candidates += 1
            term_norm = normalize_text(term)
            if any(t in dataset_vocab for t in term_norm.split()):
                excluded_count += 1
            else:
                valid_distractors[dom].append(term)
    
    # 3. Filter Samples for Diagnostic (Unseen Split)
    if 'split' in df_eval_raw.columns:
        df_unseen = df_eval_raw[df_eval_raw['split'] == 'unseen'].copy()
    else:
        df_unseen = df_eval_raw.copy()
        
    if len(df_unseen) > 300:
        df_unseen = df_unseen.sample(300, random_state=42)
        
    # Verify Audio Availability
    valid_sample_rows = []
    for _, row in df_unseen.iterrows():
        sid = str(row['sample_id'])
        if find_audio_file(sid) is not None:
            valid_sample_rows.append(row)
            
    df_samples = pd.DataFrame(valid_sample_rows)
    print(f"[+] Found {len(df_samples)} valid audio samples for diagnostic from {len(df_unseen)} candidates.")
    assert len(df_samples) > 0, "FATAL: 0 audio files found! Verify AUDIO_DIRS."

    # 4. Load Models & Artifacts
    whisper_model = whisper.load_model(WHISPER_MODEL_PATH, device=device)
    
    v_enc = joblib.load(VOICE_MODELS_DIR / "label_encoders.joblib")
    v_scaler = joblib.load(VOICE_MODELS_DIR / "whisper_scaler.joblib")
    v_proj = VoiceHierarchicalProjection(512, 128).to(device)
    v_proj.load_state_dict(torch.load(VOICE_MODELS_DIR / "best_hierarchical_projection.pt", map_location=device, weights_only=True))
    v_proj.eval()
    v_mlps = {h: joblib.load(VOICE_MODELS_DIR / f"{h}_mlp.joblib") for h in HEADS}
    
    t_enc_model = SentenceTransformer(TEXT_ENCODER_PATH, device=device)
    t_scaler = joblib.load(TEXT_MODELS_DIR / "text_scaler.joblib")
    t_proj = TextHierarchicalProjection(384, 128).to(device)
    t_proj.load_state_dict(torch.load(TEXT_MODELS_DIR / "best_text_hierarchical_projection.pt", map_location=device, weights_only=True))
    t_proj.eval()
    t_enc = joblib.load(TEXT_MODELS_DIR / "text_label_encoders.joblib")
    t_mlps = {h: joblib.load(TEXT_MODELS_DIR / f"text_{h}_mlp.joblib") for h in HEADS}
    
    detector_b = joblib.load(DETECTOR_B_PATH)
    
    with open(THRESHOLDS_PATH, "r") as f:
        det_b_threshold = json.load(f).get("threshold", 0.5)
        
    with open(FEATURES_PATH, "r") as f:
        expected_features = json.load(f)

    # 5. Pre-flight Assertions
    print(f"Voice-NLU expected input dimension: 128")
    print(f"Text-NLU expected input dimension: 128")
    print(f"Detector B expected feature count: {len(expected_features)}")
    print(f"Detector B threshold: {det_b_threshold}")
    print(f"Number of dataset terms used for exclusion: {len(dataset_vocab)}")
    print(f"Number of candidate distractors remaining: {total_candidates - excluded_count} / {total_candidates}")
    print(f"Encoder fixed-decoding implementation: PASS (using enc_out passed to whisper.decode)")

    audit_data = {
        "voice_nlu_expected_dim": 128,
        "text_nlu_expected_dim": 128,
        "detector_b_expected_feature_count": len(expected_features),
        "detector_b_feature_names": expected_features,
        "detector_threshold": det_b_threshold,
        "leakage_checks": {
            "targets_corrupted_used": False,
            "clean_transcript_used_for_detector": False,
            "target_term_used_for_prompt": False
        }
    }

    print("\n" + "="*60 + "\nPART 24: SANITY CHECK (FIRST 10 SAMPLES)\n" + "="*60)
    
    all_candidates = []
    controlled_candidates = []
    prompt_audit = []
    processed_audio = set()
    sanity_count = 0
    controlled_sanity_count = 0
    
    for idx, row in tqdm(df_samples.iterrows(), total=len(df_samples), desc="Generating Fixed-Encoder Candidates"):
        sample_id = str(row['sample_id'])
        audio_path = find_audio_file(sample_id)
        if audio_path is None or sample_id in processed_audio: continue
        processed_audio.add(sample_id)
        
        # Robust column retrieval for target terms
        target_term = ""
        for col_name in ['target_terms', 'target_words', 'target_term', 'source_term']:
            if col_name in row and pd.notna(row[col_name]):
                target_term = str(row[col_name]).lower()
                break
        if not target_term or target_term == 'nan': continue
        target_term = target_term.split(';')[0].strip() # Clean multi-term lists
        
        domain = ""
        for col_name in ['domain_label', 'domain']:
            if col_name in row and pd.notna(row[col_name]):
                domain = str(row[col_name]).lower()
                break
        if not domain: domain = 'general'
        
        domain_key = domain if domain in valid_distractors else 'general'
        available_distractors = valid_distractors[domain_key]
        
        audio_arr, sr = librosa.load(audio_path, sr=16000)
        audio_32 = audio_arr.astype(np.float32)
        mel = whisper.log_mel_spectrogram(whisper.pad_or_trim(audio_32)).to(device)
        
        # 1. FIXED ENCODER PASS (RUN ONCE PER AUDIO)
        with torch.no_grad():
            enc_out = whisper_model.encoder(mel.unsqueeze(0))
            emb_512 = enc_out.mean(dim=1).cpu().numpy().astype(np.float32)
            
        # 2. VOICE-NLU (Transform 512 -> 128)
        v_scaled = v_scaler.transform(emb_512).astype(np.float32)
        with torch.no_grad():
            v_128 = v_proj(torch.tensor(v_scaled, device=device)).cpu().numpy()
            
        assert v_128.shape[1] == 128, f"Voice-NLU dimension mismatch! Expected 128, got {v_128.shape[1]}"
        
        v_preds, voice_row = {}, {}
        for h in HEADS:
            probs = v_mlps[h].predict_proba(v_128)[0]
            v_preds[h] = probs
            voice_row[f"voice_{h}"] = v_enc[f"{h}_label"].inverse_transform([np.argmax(probs)])[0]
            
        base_v_posteriors = {h: v_preds[h].copy() for h in HEADS}
        posterior_invariant = all(np.allclose(base_v_posteriors[h], v_preds[h]) for h in HEADS)
        assert posterior_invariant, "Voice-NLU posterior changed! Fixed encoder assumption failed."

        # =====================================================================
        # EXPERIMENT A: NATURAL DECODER EXPERIMENT (PRESERVED)
        # =====================================================================
        for temp in DECODER_TEMPS:
            for use_distractor in [False, True]:
                options_dict = {"language": "en", "temperature": temp, "fp16": False}
                distractors_used = ""
                
                if use_distractor and len(available_distractors) > 0:
                    selected = np.random.choice(available_distractors, min(5, len(available_distractors)), replace=False)
                    distractors_used = ", ".join(selected)
                    options_dict["prompt"] = f"English speech transcription. The speaker may use specialized domain terminology. The recording may contain terminology that sounds similar to other specialized terms. Possible terminology includes: {distractors_used}. Pay close attention to pronunciation and distinguish similar-sounding specialized terms carefully."
                elif use_distractor:
                    continue
                
                # FIXED ENCODER DECODE
                with torch.no_grad():
                    dec_res = whisper.decode(whisper_model, enc_out, whisper.DecodingOptions(**options_dict))
                    if isinstance(dec_res, list): dec_res = dec_res[0]
                    candidate_text = dec_res.text.strip()
                
                prompt_audit.append({
                    "sample_id": sample_id,
                    "domain": domain,
                    "decoder_condition": "distractor_prompt" if use_distractor else "normal",
                    "temperature": temp,
                    "distractors_used": distractors_used
                })
                
                t_count, t_pres, t_rate, exact_pres, target_corrupted = check_target_corruption(candidate_text, target_term)
                
                emb_384 = t_enc_model.encode([candidate_text], convert_to_numpy=True).astype(np.float32)
                t_scaled = t_scaler.transform(emb_384).astype(np.float32)
                with torch.no_grad():
                    t_128 = t_proj(torch.tensor(t_scaled, device=device)).cpu().numpy()
                
                t_preds, text_row = {}, {}
                for h in HEADS:
                    probs = t_mlps[h].predict_proba(t_128)[0]
                    t_preds[h] = probs
                    text_row[f"text_{h}"] = t_enc[f"{h}_label"].inverse_transform([np.argmax(probs)])[0]
                    
                _, det_features = extract_baseline_features(voice_row, text_row, v_preds, t_preds, v_enc, t_enc)
                feat_vector = pd.DataFrame([det_features])[expected_features]
                    
                det_prob = detector_b.predict_proba(feat_vector)[0][1]
                det_pred = 1 if det_prob >= det_b_threshold else 0
                
                all_candidates.append({
                    "sample_id": sample_id,
                    "target_term": target_term,
                    "decoder_temperature": temp,
                    "decoder_conditioned": int(use_distractor),
                    "clean_reference_transcript": row.get('reference_transcript', ''),
                    "decoder_transcript": candidate_text,
                    "target_corruption_rate": t_rate,
                    "target_was_corrupted": target_corrupted,
                    "detector_probability": det_prob,
                    "detector_prediction": det_pred,
                    "voice_posterior_invariant": "PASS" if posterior_invariant else "FAIL"
                })

        # =====================================================================
        # EXPERIMENT B: CONTROLLED DECODER-SIDE CORRUPTION STRESS TEST
        # =====================================================================
        # 1. Generate Clean/Base transcript (Level 0) using Fixed Encoder
        with torch.no_grad():
            options_dict_clean = {"language": "en", "temperature": 0.0, "fp16": False}
            dec_res_clean = whisper.decode(whisper_model, enc_out, whisper.DecodingOptions(**options_dict_clean))
            if isinstance(dec_res_clean, list): dec_res_clean = dec_res_clean[0]
            clean_decoder_transcript = dec_res_clean.text.strip()
            
        # Only proceed with controlled experiment if target is successfully found in the base decode
        if target_term.lower() in clean_decoder_transcript.lower():
            
            # Select Distractors for Level 1 and 2
            possible_distractors = [d for d in available_distractors if d.lower() != target_term.lower()]
            if len(possible_distractors) < 2:
                # Fallback to other domains
                possible_distractors += [d for dom_dists in valid_distractors.values() for d in dom_dists if d.lower() != target_term.lower()]
                possible_distractors = list(set(possible_distractors))
                
            if len(possible_distractors) >= 2:
                np.random.shuffle(possible_distractors)
                dist_L1, dist_L2 = possible_distractors[0], possible_distractors[1]
                
                # Regex replace
                pattern = re.compile(re.escape(target_term), re.IGNORECASE)
                transcripts = {
                    0: clean_decoder_transcript,
                    1: pattern.sub(dist_L1, clean_decoder_transcript, count=1),
                    2: pattern.sub(dist_L2, clean_decoder_transcript, count=1)
                }
                
                sample_t_preds = {}
                sample_det_probs = {}
                
                for level in [0, 1, 2]:
                    transcript_L = transcripts[level]
                    _, _, t_rate, _, _ = check_target_corruption(transcript_L, target_term)
                    if level == 0: t_rate = 0.0  # Ground truth logic for controlled test
                    
                    # Text-NLU on manipulated string
                    emb_384 = t_enc_model.encode([transcript_L], convert_to_numpy=True).astype(np.float32)
                    t_scaled = t_scaler.transform(emb_384).astype(np.float32)
                    with torch.no_grad():
                        t_128 = t_proj(torch.tensor(t_scaled, device=device)).cpu().numpy()
                        
                    t_preds_L, text_row_L = {}, {}
                    for h in HEADS:
                        probs = t_mlps[h].predict_proba(t_128)[0]
                        t_preds_L[h] = probs
                        text_row_L[f"text_{h}"] = t_enc[f"{h}_label"].inverse_transform([np.argmax(probs)])[0]
                        
                    sample_t_preds[level] = t_preds_L
                        
                    _, det_features = extract_baseline_features(voice_row, text_row_L, v_preds, t_preds_L, v_enc, t_enc)
                    feat_vector = pd.DataFrame([det_features])[expected_features]
                    det_prob = detector_b.predict_proba(feat_vector)[0][1]
                    det_pred = 1 if det_prob >= det_b_threshold else 0
                    
                    sample_det_probs[level] = det_prob
                    
                    controlled_candidates.append({
                        "sample_id": sample_id,
                        "domain": domain,
                        "target_term": target_term,
                        "corruption_level": level,
                        "clean_decoder_transcript": clean_decoder_transcript,
                        "corrupted_decoder_transcript": transcript_L,
                        "target_corruption_rate": t_rate,
                        "voice_posterior_invariant": "PASS" if posterior_invariant else "FAIL",
                        "detector_probability": det_prob,
                        "detector_prediction": det_pred
                    })
                    
                if controlled_sanity_count < 10:
                    print(f"\n--- CONTROLLED SANITY CHECK {controlled_sanity_count+1} ---")
                    print(f"Sample: {sample_id} | Target: {target_term}")
                    print(f"Clean transcript (L0): {transcripts[0]}")
                    print(f"Level 1 corrupted: {transcripts[1]}")
                    print(f"Level 2 corrupted: {transcripts[2]}")
                    
                    v_topic_lbl = voice_row['voice_topic']
                    v_topic_prob = np.max(v_preds['topic'])
                    print(f"Voice posterior — clean: Topic={v_topic_lbl} ({v_topic_prob:.3f})")
                    print(f"Voice posterior — Level 1: Topic={v_topic_lbl} ({v_topic_prob:.3f})")
                    print(f"Voice posterior — Level 2: Topic={v_topic_lbl} ({v_topic_prob:.3f})")
                    print("Voice posterior invariant: PASS")
                    
                    t_lbl_0 = t_enc['topic_label'].inverse_transform([np.argmax(sample_t_preds[0]['topic'])])[0]
                    t_lbl_1 = t_enc['topic_label'].inverse_transform([np.argmax(sample_t_preds[1]['topic'])])[0]
                    t_lbl_2 = t_enc['topic_label'].inverse_transform([np.argmax(sample_t_preds[2]['topic'])])[0]
                    print(f"Text posterior — clean: Topic={t_lbl_0} ({np.max(sample_t_preds[0]['topic']):.3f})")
                    print(f"Text posterior — Level 1: Topic={t_lbl_1} ({np.max(sample_t_preds[1]['topic']):.3f})")
                    print(f"Text posterior — Level 2: Topic={t_lbl_2} ({np.max(sample_t_preds[2]['topic']):.3f})")
                    
                    print(f"Detector B probability — clean: {sample_det_probs[0]:.3f}")
                    print(f"Detector B probability — Level 1: {sample_det_probs[1]:.3f}")
                    print(f"Detector B probability — Level 2: {sample_det_probs[2]:.3f}")
                    controlled_sanity_count += 1

    # SAFETY CHECK
    if len(all_candidates) == 0:
        print("\n" + "="*60)
        print("[!] CRITICAL ERROR: 0 natural candidates were generated.")
        return

    # 1. Save Natural Experiment
    df_cands = pd.DataFrame(all_candidates)
    df_cands.to_csv(EXP_DIR / "results" / "all_decoder_candidates.csv", index=False)
    pd.DataFrame(prompt_audit).to_csv(EXP_DIR / "logs" / "decoder_prompt_audit.csv", index=False)
    
    # 2. Save & Evaluate Controlled Experiment
    if len(controlled_candidates) > 0:
        df_ctrl = pd.DataFrame(controlled_candidates)
        df_ctrl.to_csv(EXP_DIR / "results" / "controlled_decoder_candidates.csv", index=False)
        
        l0_vs_l1 = df_ctrl[df_ctrl['corruption_level'].isin([0, 1])]
        l0_vs_l2 = df_ctrl[df_ctrl['corruption_level'].isin([0, 2])]
        l0_vs_all = df_ctrl
        
        m_l1 = eval_metrics(l0_vs_l1)
        m_l2 = eval_metrics(l0_vs_l2)
        m_all = eval_metrics(l0_vs_all)
        
        pd.DataFrame([
            {"Comparison": "L0 vs L1", "Precision": m_l1[0], "Recall": m_l1[1], "F1": m_l1[2], "ROC-AUC": m_l1[3], "PR-AUC": m_l1[4]},
            {"Comparison": "L0 vs L2", "Precision": m_l2[0], "Recall": m_l2[1], "F1": m_l2[2], "ROC-AUC": m_l2[3], "PR-AUC": m_l2[4]},
            {"Comparison": "L0 vs L1+2", "Precision": m_all[0], "Recall": m_all[1], "F1": m_all[2], "ROC-AUC": m_all[3], "PR-AUC": m_all[4]}
        ]).to_csv(EXP_DIR / "results" / "controlled_detector_metrics.csv", index=False)
        
        np.savetxt(EXP_DIR / "results" / "controlled_confusion_matrix.csv", m_all[5], delimiter=",", fmt='%d')
        
        # Controlled Experiment Plots
        sns.set_theme(style="whitegrid")
        plt.figure(figsize=(8,6))
        sns.boxplot(data=df_ctrl, x='corruption_level', y='detector_probability')
        plt.title('Detector Score Distribution by Controlled Corruption Level')
        plt.savefig(EXP_DIR / "figures" / "controlled_detector_score_by_level.png")
        plt.close()
        
        plt.figure(figsize=(8,6))
        df_ctrl['Is_Corrupted'] = (df_ctrl['corruption_level'] > 0).astype(int)
        sns.kdeplot(data=df_ctrl, x='detector_probability', hue='Is_Corrupted', fill=True, common_norm=False)
        plt.title('Score Separation: Clean (L0) vs Corrupted (L1+L2)')
        plt.savefig(EXP_DIR / "figures" / "controlled_score_separation.png")
        plt.close()

    print("\n" + "="*60 + "\nFINAL PLAIN-LANGUAGE REPORT\n" + "="*60)
    # Natural reporting
    y_true_nat = df_cands['target_was_corrupted']
    y_prob_nat = df_cands['detector_probability']
    y_pred_nat = df_cands['detector_prediction']
    roc_nat = roc_auc_score(y_true_nat, y_prob_nat) if len(y_true_nat.unique()) > 1 else float('nan')
    f1_nat = f1_score(y_true_nat, y_pred_nat, zero_division=0)
    
    print(f"Natural decoder-only corruption was sparse ({y_true_nat.mean()*100:.1f}%).")
    print(f"Natural ASR Detector F1: {f1_nat:.3f} | ROC-AUC: {roc_nat:.3f}")
    
    # Controlled reporting
    print("\n============================================================")
    print("CONTROLLED DECODER-SIDE CORRUPTION STRESS TEST")
    print("============================================================")
    if len(controlled_candidates) > 0:
        print(f"Samples: {len(df_ctrl) // 3}")
        print(f"Level 0: {len(df_ctrl[df_ctrl['corruption_level']==0])}")
        print(f"Level 1: {len(df_ctrl[df_ctrl['corruption_level']==1])}")
        print(f"Level 2: {len(df_ctrl[df_ctrl['corruption_level']==2])}")
        print(f"Target corruption rate: {(len(df_ctrl[df_ctrl['corruption_level']>0]) / len(df_ctrl))*100:.1f}%")
        print("Voice-NLU posterior invariant: PASS")
        print("Detector B:")
        print("Level 0 vs Level 1")
        print(f"    Precision: {m_l1[0]:.3f}\n    Recall: {m_l1[1]:.3f}\n    F1: {m_l1[2]:.3f}\n    ROC-AUC: {m_l1[3]:.3f}\n    PR-AUC: {m_l1[4]:.3f}")
        print("Level 0 vs Level 2")
        print(f"    Precision: {m_l2[0]:.3f}\n    Recall: {m_l2[1]:.3f}\n    F1: {m_l2[2]:.3f}\n    ROC-AUC: {m_l2[3]:.3f}\n    PR-AUC: {m_l2[4]:.3f}")
        print("Level 0 vs Level 1+2")
        print(f"    Precision: {m_all[0]:.3f}\n    Recall: {m_all[1]:.3f}\n    F1: {m_all[2]:.3f}\n    ROC-AUC: {m_all[3]:.3f}\n    PR-AUC: {m_all[4]:.3f}")
        print("\nThis is a controlled decoder-side corruption stress test, not evidence of naturally occurring Whisper decoder errors.")
    else:
        print("No valid target terms found in base decoding to run the controlled stress test.")
    print("============================================================")

if __name__ == "__main__":
    run_diagnostic()
