"""
decoder_only_detector_diagnostic.py

Time-critical final diagnostic for downstream reasoning feasibility.
Tests whether the existing ASR Error Detector B can identify decoder-level 
lexical errors when the Whisper ENCODER REPRESENTATION IS HELD FIXED.
"""

import os
import re
import json
import warnings
import numpy as np
import pandas as pd
import librosa
import torch
import whisper
import joblib
from pathlib import Path
from tqdm import tqdm
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, auc, precision_recall_curve
from scipy.spatial.distance import jensenshannon
from sentence_transformers import SentenceTransformer
import torch.nn as nn
import torch.nn.functional as F

# Import authoritative feature extractor
from feature_extractor import extract_baseline_features

warnings.filterwarnings("ignore")

# ==========================================
# 0. CONFIGURATION & PATHS
# ==========================================
ROOT_DIR = Path("/home/spark2/users/intern/Atreyee-Das/NLU_Robust_Experiment")
DATASET_CSV = ROOT_DIR / "dataset" / "robus_nlu_6000_paraphrase_scenario.csv"
AUDIO_DIR = ROOT_DIR / "audio"

WHISPER_MODEL_PATH = "/home/spark2/Models/base.en.pt"
VOICE_MODELS_DIR = ROOT_DIR / "audio_nlu_models"
TEXT_MODELS_DIR = ROOT_DIR / "text_nlu_models"
TEXT_ENCODER_PATH = "/home/spark2/Models/all-MiniLM-L6-v2"

# Artifacts generated by run_master_exp.py
EXP_BASE = ROOT_DIR / "error_detector_experiments"
MODELS_CACHE_DIR = EXP_BASE / "artifacts" / "models"
DETECTOR_B_PATH = MODELS_CACHE_DIR / "real_whisper_detector_B.joblib"
THRESHOLDS_PATH = MODELS_CACHE_DIR / "real_whisper_detector_B_threshold.json"
FEATURES_PATH = MODELS_CACHE_DIR / "real_whisper_detector_B_features.json"

EXP_DIR = Path("decoder_only_detector_diagnostic")
for sub in ["results", "posterior_npz", "representative", "figures", "logs"]:
    (EXP_DIR / sub).mkdir(parents=True, exist_ok=True)

HEADS = ["domain", "subdomain", "topic", "document_type"]
DECODER_TEMPS = [0.0, 0.2, 0.4, 0.6, 0.8]

# ==========================================
# 1. ARCHITECTURE DEFINITIONS
# ==========================================
class VoiceHierarchicalProjection(nn.Module):
    def __init__(self, input_dim=512, projection_dim=128):
        super().__init__()
        self.projector = nn.Sequential(
            nn.Linear(input_dim, 256),
            nn.ReLU(),
            nn.Dropout(0.10),
            nn.Linear(256, projection_dim),
        )
    def forward(self, x):
        z = self.projector(x)
        return F.normalize(z, p=2, dim=1)

class TextHierarchicalProjection(nn.Module):
    def __init__(self, input_dim=384, projection_dim=128):
        super().__init__()
        self.projector = nn.Sequential(
            nn.Linear(input_dim, 256),
            nn.ReLU(),
            nn.Dropout(0.10),
            nn.Linear(256, projection_dim),
        )
    def forward(self, x):
        z = self.projector(x)
        return F.normalize(z, p=2, dim=1)

# ==========================================
# 2. DISTRACTOR & TEXT HELPERS
# ==========================================
CANDIDATE_DISTRACTORS = {
    "medical": [
        "myocardial ischemia", "cardiac insufficiency", "coronary stenosis", 
        "ventricular arrhythmia", "pericardial inflammation", "arterial occlusion", 
        "vascular calcification", "cardiac electrophysiology", "pulmonary embolism", 
        "hemodynamic instability"
    ],
    "finance": [
        "claims adjudication", "provider reimbursement", "premium reconciliation", 
        "medical billing adjustment", "benefit authorization", "clinical payment settlement", 
        "payer reconciliation", "hospital revenue cycle", "insurance eligibility", 
        "healthcare reimbursement", "algorithmic trading", "digital asset custody", 
        "technology investment banking", "cloud infrastructure financing", 
        "software revenue recognition", "electronic settlement", "cybersecurity financing", 
        "technology capital allocation", "digital payment infrastructure", "fintech risk management",
        "industrial procurement", "manufacturing capital expenditure", "equipment depreciation", 
        "supply chain financing", "factory asset valuation", "industrial inventory turnover", 
        "machinery leasing", "production capacity financing", "commodity procurement", 
        "industrial working capital"
    ],
    "general": [
        "appointment confirmation", "reservation cancellation", "customer service request", 
        "delivery notification", "account verification", "schedule modification", 
        "payment confirmation", "booking information", "service availability", "order confirmation"
    ]
}

def normalize_text(text):
    if not isinstance(text, str): return ""
    text = text.lower()
    text = re.sub(r'[^\w\s]', '', text)
    text = re.sub(r'\s+', ' ', text)
    return text.strip()

def build_dataset_vocabulary(df):
    vocab = set()
    text_cols = [c for c in df.columns if 'transcript' in c or 'target' in c or 'term' in c]
    for col in text_cols:
        for val in df[col].dropna():
            norm_val = normalize_text(str(val))
            vocab.update(norm_val.split())
    return vocab

def check_target_corruption(candidate_text, target_term):
    cand_norm = normalize_text(candidate_text)
    targ_norm = normalize_text(target_term)
    
    targ_tokens = targ_norm.split()
    cand_tokens = cand_norm.split()
    
    if not targ_tokens: return 0, 0, 0.0, 0, 0
        
    target_token_count = len(targ_tokens)
    target_tokens_preserved = sum(1 for t in targ_tokens if t in cand_tokens)
    target_corruption_rate = 1.0 - (target_tokens_preserved / target_token_count)
    exact_target_preserved = 1 if targ_norm in cand_norm else 0
    target_was_corrupted = 1 if target_corruption_rate > 0 else 0
    
    return target_token_count, target_tokens_preserved, target_corruption_rate, exact_target_preserved, target_was_corrupted

# ==========================================
# 3. MAIN EXPERIMENT
# ==========================================
def run_diagnostic():
    print("="*60 + "\nPART 1: ARTIFACT AUDIT & LOADING\n" + "="*60)
    device = "cuda" if torch.cuda.is_available() else "cpu"
    
    # 1. Dataset & Distractor Verification
    df = pd.read_csv(DATASET_CSV)
    df_unseen = df[df['split'] == 'unseen'].copy()
    
    dataset_vocab = build_dataset_vocabulary(df)
    valid_distractors = {}
    total_candidates = 0
    excluded_count = 0
    
    for dom, terms in CANDIDATE_DISTRACTORS.items():
        valid_distractors[dom] = []
        for term in terms:
            total_candidates += 1
            term_norm = normalize_text(term)
            if any(t in dataset_vocab for t in term_norm.split()):
                excluded_count += 1
            else:
                valid_distractors[dom].append(term)
    
    # 2. Load Whisper
    whisper_model = whisper.load_model(WHISPER_MODEL_PATH, device=device)
    
    # 3. Load Voice-NLU Artifacts
    v_enc = joblib.load(VOICE_MODELS_DIR / "label_encoders.joblib")
    v_scaler = joblib.load(VOICE_MODELS_DIR / "whisper_scaler.joblib")
    v_proj = VoiceHierarchicalProjection(512, 128).to(device)
    v_proj.load_state_dict(torch.load(VOICE_MODELS_DIR / "best_hierarchical_projection.pt", map_location=device, weights_only=True))
    v_proj.eval()
    v_mlps = {h: joblib.load(VOICE_MODELS_DIR / f"{h}_mlp.joblib") for h in HEADS}
    
    # 4. Load Text-NLU Artifacts
    t_enc_model = SentenceTransformer(TEXT_ENCODER_PATH, device=device)
    t_scaler = joblib.load(TEXT_MODELS_DIR / "text_scaler.joblib")
    t_proj = TextHierarchicalProjection(384, 128).to(device)
    t_proj.load_state_dict(torch.load(TEXT_MODELS_DIR / "best_text_hierarchical_projection.pt", map_location=device, weights_only=True))
    t_proj.eval()
    t_enc = joblib.load(TEXT_MODELS_DIR / "text_label_encoders.joblib")
    t_mlps = {h: joblib.load(TEXT_MODELS_DIR / f"text_{h}_mlp.joblib") for h in HEADS}
    
    # 5. Load Detector B
    detector_b = joblib.load(DETECTOR_B_PATH)
    
    with open(THRESHOLDS_PATH, "r") as f:
        det_b_threshold = json.load(f).get("threshold", 0.5)
        
    with open(FEATURES_PATH, "r") as f:
        expected_features = json.load(f)

    # 6. Pre-flight Assertions
    print(f"Voice-NLU expected input dimension: 128")
    print(f"Text-NLU expected input dimension: 128")
    print(f"Detector B expected feature count: {len(expected_features)}")
    print(f"Detector B threshold: {det_b_threshold}")
    print(f"Number of dataset terms used for exclusion: {len(dataset_vocab)}")
    print(f"Number of candidate distractors remaining: {total_candidates - excluded_count} / {total_candidates}")
    print(f"Encoder fixed-decoding implementation: PASS (using enc_out passed to whisper.decode)")
    
    # Prepare feature audit output
    audit_data = {
        "voice_nlu_expected_dim": 128,
        "text_nlu_expected_dim": 128,
        "detector_b_expected_feature_count": len(expected_features),
        "detector_b_feature_names": expected_features,
        "detector_threshold": det_b_threshold,
        "leakage_checks": {
            "targets_corrupted_used": False,
            "clean_transcript_used_for_detector": False,
            "target_term_used_for_prompt": False
        }
    }

    print("\n" + "="*60 + "\nPART 24: SANITY CHECK (FIRST 10 SAMPLES)\n" + "="*60)
    all_candidates = []
    prompt_audit = []
    processed_audio = set()
    sanity_count = 0
    
    if len(df_unseen) > 300: df_unseen = df_unseen.sample(300, random_state=42)
    
    for idx, row in tqdm(df_unseen.iterrows(), total=len(df_unseen), desc="Generating Fixed-Encoder Candidates"):
        sample_id = str(row['sample_id'])
        audio_path = AUDIO_DIR / f"{sample_id}.wav"
        if not audio_path.exists() or sample_id in processed_audio: continue
        processed_audio.add(sample_id)
        
        target_term = str(row.get('target_terms', row.get('source_term', ''))).lower()
        if not target_term or target_term == 'nan': continue
        
        domain = str(row.get('domain_label', row.get('domain', 'general'))).lower()
        domain_key = domain if domain in valid_distractors else 'general'
        available_distractors = valid_distractors[domain_key]
        
        audio_arr, sr = librosa.load(audio_path, sr=16000)
        audio_32 = audio_arr.astype(np.float32)
        mel = whisper.log_mel_spectrogram(whisper.pad_or_trim(audio_32)).to(device)
        
        # 1. FIXED ENCODER PASS (RUN ONCE)
        with torch.no_grad():
            enc_out = whisper_model.encoder(mel.unsqueeze(0))
            emb_512 = enc_out.mean(dim=1).cpu().numpy().astype(np.float32)
            
        # 2. VOICE-NLU (Transform 512 -> 128)
        v_scaled = v_scaler.transform(emb_512).astype(np.float32)
        with torch.no_grad():
            v_128 = v_proj(torch.tensor(v_scaled, device=device)).cpu().numpy()
            
        assert v_128.shape[1] == 128, f"Voice-NLU dimension mismatch! Expected 128, got {v_128.shape[1]}"
        
        v_preds, voice_row = {}, {}
        for h in HEADS:
            probs = v_mlps[h].predict_proba(v_128)[0]
            v_preds[h] = probs
            voice_row[f"voice_{h}"] = v_enc[f"{h}_label"].inverse_transform([np.argmax(probs)])[0]
            
        # 3. DECODER VARIATION (Fixed Encoder)
        base_v_posteriors = {h: v_preds[h].copy() for h in HEADS}
        
        for temp in DECODER_TEMPS:
            for use_distractor in [False, True]:
                options_dict = {"language": "en", "temperature": temp, "fp16": False}
                distractors_used = ""
                
                if use_distractor and len(available_distractors) > 0:
                    selected = np.random.choice(available_distractors, min(5, len(available_distractors)), replace=False)
                    distractors_used = ", ".join(selected)
                    options_dict["initial_prompt"] = f"English speech transcription. The speaker may use specialized domain terminology. The recording may contain terminology that sounds similar to other specialized terms. Possible terminology includes: {distractors_used}. Pay close attention to pronunciation and distinguish similar-sounding specialized terms carefully."
                elif use_distractor:
                    continue # Skip if no distractors available
                
                # FIXED ENCODER DECODE: Pass enc_out instead of mel
                with torch.no_grad():
                    dec_res = whisper.decode(whisper_model, enc_out, whisper.DecodingOptions(**options_dict))
                    candidate_text = dec_res.text.strip()
                
                prompt_audit.append({
                    "sample_id": sample_id,
                    "domain": domain,
                    "decoder_condition": "distractor_prompt" if use_distractor else "normal",
                    "temperature": temp,
                    "distractors_used": distractors_used
                })
                
                # 4. TARGET CORRUPTION CHECK (Diagnostic Truth ONLY)
                t_count, t_pres, t_rate, exact_pres, target_corrupted = check_target_corruption(candidate_text, target_term)
                
                # 5. TEXT-NLU (Transform 384 -> 128)
                emb_384 = t_enc_model.encode([candidate_text], convert_to_numpy=True).astype(np.float32)
                t_scaled = t_scaler.transform(emb_384).astype(np.float32)
                with torch.no_grad():
                    t_128 = t_proj(torch.tensor(t_scaled, device=device)).cpu().numpy()
                
                assert t_128.shape[1] == 128, f"Text-NLU dimension mismatch! Expected 128, got {t_128.shape[1]}"
                
                t_preds, text_row = {}, {}
                for h in HEADS:
                    probs = t_mlps[h].predict_proba(t_128)[0]
                    t_preds[h] = probs
                    text_row[f"text_{h}"] = t_enc[f"{h}_label"].inverse_transform([np.argmax(probs)])[0]
                    
                # 6. EXACT DETECTOR B FEATURES
                _, det_features = extract_baseline_features(
                    voice_row, text_row, v_preds, t_preds, v_enc, t_enc
                )
                
                feat_vector = pd.DataFrame([det_features])[expected_features]
                assert feat_vector.shape[1] == len(expected_features), "Detector B feature dimension mismatch!"
                    
                det_prob = detector_b.predict_proba(feat_vector)[0][1]
                det_pred = 1 if det_prob >= det_b_threshold else 0
                
                cand_data = {
                    "sample_id": sample_id,
                    "target_term": target_term,
                    "decoder_temperature": temp,
                    "decoder_conditioned": int(use_distractor),
                    "clean_reference_transcript": row.get('reference_transcript', ''),
                    "decoder_transcript": candidate_text,
                    "target_corruption_rate": t_rate,
                    "target_was_corrupted": target_corrupted,
                    "detector_probability": det_prob,
                    "detector_prediction": det_pred
                }
                
                # Verify Invariance Check
                posterior_invariant = all(np.allclose(base_v_posteriors[h], v_preds[h]) for h in HEADS)
                cand_data["voice_posterior_invariant"] = "PASS" if posterior_invariant else "FAIL"
                assert posterior_invariant, "Voice-NLU posterior changed! Fixed encoder assumption failed."

                all_candidates.append(cand_data)
                
                if sanity_count < 10:
                    print(f"\n--- SANITY CHECK {sanity_count+1} ---")
                    print(f"Sample: {sample_id} | Domain: {domain}")
                    print(f"Target: {target_term} | Temp: {temp} | Cond: {'distractor' if use_distractor else 'normal'}")
                    print(f"Transcript: {candidate_text}")
                    print(f"Target Corrupted: {target_corrupted}")
                    print(f"Encoder Shape: {enc_out.shape} | Voice Dim: {v_128.shape} | Text Dim: {t_128.shape}")
                    print(f"Voice Topic: {voice_row['voice_topic']} | Text Topic: {text_row['text_topic']}")
                    print(f"Det Features Count: {feat_vector.shape[1]} | Det Prob: {det_prob:.3f} | Pred: {det_pred}")
                    print(f"Voice-NLU posterior invariant: {cand_data['voice_posterior_invariant']}")
                    sanity_count += 1

    df_cands = pd.DataFrame(all_candidates)
    df_cands.to_csv(EXP_DIR / "results" / "all_decoder_candidates.csv", index=False)
    
    pd.DataFrame(prompt_audit).to_csv(EXP_DIR / "logs" / "decoder_prompt_audit.csv", index=False)
    
    audit_data["samples_processed"] = len(processed_audio)
    audit_data["decoder_candidates_evaluated"] = len(df_cands)
    audit_data["actual_runtime_feature_count"] = feat_vector.shape[1]
    
    with open(EXP_DIR / "logs" / "runtime_feature_audit.json", "w") as f:
        json.dump(audit_data, f, indent=4)
    
    print("\n" + "="*60 + "\nPART 13: EVALUATE DETECTOR B\n" + "="*60)
    
    y_true = df_cands['target_was_corrupted']
    y_prob = df_cands['detector_probability']
    y_pred = df_cands['detector_prediction']
    
    if len(y_true.unique()) > 1:
        roc_auc = roc_auc_score(y_true, y_prob)
        precision, recall, _ = precision_recall_curve(y_true, y_prob)
        pr_auc = auc(recall, precision)
    else:
        roc_auc = pr_auc = float('nan')
        
    metrics = {
        "Accuracy": accuracy_score(y_true, y_pred),
        "Precision": precision_score(y_true, y_pred, zero_division=0),
        "Recall": recall_score(y_true, y_pred, zero_division=0),
        "F1": f1_score(y_true, y_pred, zero_division=0),
        "ROC-AUC": roc_auc,
        "PR-AUC": pr_auc
    }
    pd.DataFrame([metrics]).to_csv(EXP_DIR / "results" / "detector_metrics.csv", index=False)
    
    sns.set_theme(style="whitegrid")
    plt.figure(figsize=(8,6))
    sns.kdeplot(data=df_cands, x='detector_probability', hue='target_was_corrupted', fill=True, common_norm=False)
    plt.title('Detector B Probability Separation')
    plt.savefig(EXP_DIR / "figures" / "score_separation.png")
    plt.close()

    print("\n" + "="*60 + "\nFINAL PLAIN-LANGUAGE REPORT\n" + "="*60)
    t_rate_pct = df_cands['target_was_corrupted'].mean() * 100
    
    print("What happened?")
    print(f"1. A fixed Whisper encoder representation produced {len(df_cands)} alternative decoder transcripts via temperature and distractor-prompt conditioning.")
    print(f"2. Target terms were corrupted {t_rate_pct:.1f}% of the time.")
    print(f"3. Voice-NLU inherently preserved exact original semantic information because the encoder input was locked.")
    print(f"4. Existing Detector B achieved ROC-AUC: {roc_auc:.3f} and F1: {metrics['F1']:.3f} on purely decoder-induced errors.")
    
    if metrics['F1'] > 0.65:
        print("\nNEXT STEP:\nUSE EXISTING DETECTOR B → PROCEED TO REASONING")
    else:
        print("\nNEXT STEP:\nRETRAIN DETECTOR B → THEN PROCEED TO REASONING")
    print("="*60)

if __name__ == "__main__":
    run_diagnostic()
