import os
from iti_engine import ITIPipeline
from evaluate_mucs import evaluate_ablation_arm

# --- PATH CONFIGURATION ---
XTTS_MODEL_PATH = "/home/spark2/Models/XTTS-v2"
REFERENCE_AUDIO = "/home/spark2/ICASSP_Project/Monika_lively.wav"
OUTPUT_DIR = "/home/spark2/ICASSP_Project/outputs"

# Your pre-sliced MUCS directory paths
SLICED_TEST_DIR = "/home/spark2/ICASSP_Project/MUCS_sliced/test"
TRANSCRIPTS_FILE = os.path.join(SLICED_TEST_DIR, "transcripts.txt")

os.makedirs(OUTPUT_DIR, exist_ok=True)

def load_sliced_dataset(transcripts_path):
    """Reads the tab-separated transcripts.txt generated by mucs_slicer.py"""
    dataset = []
    with open(transcripts_path, "r", encoding="utf-8") as f:
        for line in f:
            parts = line.strip().split('\t')
            if len(parts) == 2:
                utt_id, text = parts
                dataset.append((text, utt_id))
    return dataset

def main():
    print("=====================================================================")
    print("STARTING APPROACH B: INFERENCE-TIME INTERVENTION (ITI) BATCH PIPELINE")
    print("=====================================================================")
    
    # 1. Load the Sliced Dataset
    print(f"[+] Loading test dataset from {TRANSCRIPTS_FILE}...")
    test_dataset = load_sliced_dataset(TRANSCRIPTS_FILE)
    print(f"[+] Found {len(test_dataset)} utterances for evaluation.")
    
    # Limit to 10 for a quick test run. Remove `[:10]` for the full paper run.
    test_dataset_subset = test_dataset[:10] 
    
    # 2. Initialize the ITI Engine (Zero Training / Frozen Backbone)
    pipeline = ITIPipeline(
        model_path=XTTS_MODEL_PATH, 
        reference_audio_path=REFERENCE_AUDIO
    )
    
    # 3. Define Ablation Arms to Test
    # Arm 1: Full System (Transliteration + ITI + Guardrail)
    # Arm 2: Minus Guardrail (Transliteration + ITI)
    # Arm 3: Minus ITI (Transliteration + Guardrail)
    # Arm 4: Minus Orthographic Normalization (Raw Text + ITI + Guardrail)
    arms_to_test = ["Arm1", "Arm2", "Arm3", "Arm4"]
    
    # 4. Generate Audio for all Arms
    for arm in arms_to_test:
        print(f"\n[+] Generating Audio for {arm}...")
        for text, utt_id in test_dataset_subset:
            output_wav_path = os.path.join(OUTPUT_DIR, f"{arm}_{utt_id}.wav")
            
            # Skip if already generated to save time on resume
            if not os.path.exists(output_wav_path):
                pipeline.process_sentence(
                    raw_text=text, 
                    output_wav_path=output_wav_path, 
                    arm=arm
                )
                print(f"    [✓] Synthesized: {output_wav_path}")
            
    # 5. Evaluate the Results
    print("\n=====================================================================")
    print("STARTING BATCH EVALUATION (WER, SIM-R, RTF, THD)")
    print("=====================================================================")
    
    for arm in arms_to_test:
        # evaluate_ablation_arm uses your local Whisper & ECAPA-TDNN models
        evaluate_ablation_arm(arm_name=arm, test_dataset=test_dataset_subset)

if __name__ == "__main__":
    main()
